export default [
  {
    id: 1,
    category: "квартира",
    price: "45 000 000 〒",
    location: "ул. Сыганак 64",
    rooms: "3",
    want: "квартира",
  },
  {
    id: 2,
    category: "квартира",
    price: "39 000 000 〒",
    location: "Коргалжинское шоссе 6",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 3,
    category: "квартира",
    price: "38 000 000 〒",
    location: "Улица Анет Баба 13",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 4,
    category: "квартира",
    price: "33 000 000 〒",
    location: "Сарайшик 5Б",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 5,
    category: "квартира",
    price: "33 000 000 〒",
    location: "Туркестан 2",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 6,
    category: "квартира",
    price: "31 500 000 〒",
    location: "Ильяс Омаров 27",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 7,
    category: "квартира",
    price: "45 000 000 〒",
    location: "ул. Сыганак 64",
    rooms: "3",
    want: "машина",
  },
  {
    id: 8,
    category: "квартира",
    price: "44 000 000 〒",
    location: "ул.Кабанбай батыра 42",
    rooms: "3",
    want: "машина",
  },
  {
    id: 9,
    category: "квартира",
    price: "45 000 000 〒",
    location: "Тараса Шевченко 8",
    rooms: "3",
    want: "машина",
  },
  {
    id: 10,
    category: "квартира",
    price: "34 000 000 〒",
    location: "Керей-Жанибек хандар",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 11,
    category: "квартира",
    price: "43 900 000 〒",
    location: "Улы дала 42",
    rooms: "3",
    want: "квартира",
  },
  {
    id: 12,
    category: "квартира",
    price: "34 000 000 〒",
    location: "",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 13,
    category: "квартира",
    price: "36 800 000 〒",
    location: "Кенесары 65",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 14,
    category: "квартира",
    price: "33 800 000 〒",
    location: "Момышулы 13А",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 15,
    category: "квартира",
    price: "36 000 000 〒",
    location: "Букар Жырау 34",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 16,
    category: "квартира",
    price: "42 000 000 〒",
    location: "Улы дала",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 17,
    category: "квартира",
    price: "34 540 000 〒",
    location: "Байтурсынова",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 18,
    category: "квартира",
    price: "33 668 200 〒",
    location: "Тыныбаева 9",
    rooms: "1",
    want: "квартира",
  },
  {
    id: 19,
    category: "квартира",
    price: "32 000 000 〒",
    location: "Богенбай Батыр 59/1",
    rooms: "2",
    want: "квартира",
  },
  {
    id: 20,
    category: "квартира",
    price: "35 196 800 〒",
    location: "Тауелсыздык",
    rooms: "1",
    want: "квартира",
  },
  {
    id: 21,
    category: "машина",
    price: "33 500 000 〒",
    location: "Astana",
    markaAndModel: "Toyota Fortuner",
    want: "квартира",
  },
  {
    id: 22,
    category: "машина",
    price: "31 500 000 〒",
    location: "Astana",
    markaAndModel: "Lexus RX 2018",
    want: "квартира",
  },
  {
    id: 23,
    category: "машина",
    price: "35 000 000 ₸",
    location: "Astana",
    markaAndModel: "Mercedes-Benz G-Класс",
    want: "квартира",
  },
  {
    id: 24,
    category: "машина",
    price: "33 250 000 〒",
    location: "Astana",
    markaAndModel: "Hyundai Palisade 2021",
    want: "квартира",
  },
  {
    id: 25,
    category: "машина",
    price: "32 999 999 〒",
    location: "Astana",
    markaAndModel: "Toyota Highlander 2021",
    want: "квартира",
  },
  {
    id: 26,
    category: "машина",
    price: "33 500 000 〒",
    location: "Astana",
    markaAndModel: "Toyota Fortuner",
    want: "квартира",
  },
  {
    id: 27,
    category: "машина",
    price: "41 000 000 〒",
    location: "Astana",
    markaAndModel: "Infiniti QX80 2019",
    want: "квартира",
  },
  {
    id: 28,
    category: "машина",
    price: "47 000 000 ₸",
    location: "Astana",
    markaAndModel: "Mercedes-Benz S-Класс 2018",
    want: "квартира",
  },
  {
    id: 29,
    category: "машина",
    price: "37 500 000 〒",
    location: "Astana",
    markaAndModel: "Lexus RX 2021",
    want: "квартира",
  },
  {
    id: 30,
    category: "машина",
    price: "31 000 000 ₸",
    location: "Astana",
    markaAndModel: "Mercedes-Benz S-Класс 2016",
    want: "дом",
  },
  {
    id: 31,
    category: "машина",
    price: "45 000 000 ₸",
    location: "Astana",
    markaAndModel: "Audi Q5 2021",
    want: "дом",
  },
  {
    id: 32,
    category: "машина",
    price: "33 200 000 ₸",
    location: "Astana",
    markaAndModel: "Lexus ES 2021",
    want: "дом",
  },
  {
    id: 33,
    category: "машина",
    price: "46 580 000 ₸",
    location: "Astana",
    markaAndModel: "Dodge Ram 2022",
    want: "дом",
  },
  {
    id: 34,
    category: "машина",
    price: "33 500 000 ₸",
    location: "Astana",
    markaAndModel: "BMW X5 2018",
    want: "дом",
  },
  {
    id: 35,
    category: "машина",
    price: "42 000 000 ₸",
    location: "Astana",
    markaAndModel: "Toyota Land Cruiser 2017",
    want: "дом",
  },
  {
    id: 36,
    category: "машина",
    price: "37 500 000 ₸",
    location: "Astana",
    markaAndModel: "Lexus RX 2021",
    want: "дом",
  },
  {
    id: 37,
    category: "машина",
    price: "42 000 000 ₸",
    location: "Astana",
    markaAndModel: "Land Rover Range Rover Sport 2018",
    want: "дом",
  },
  {
    id: 38,
    category: "машина",
    price: "33 500 000 ₸",
    location: "Astana",
    markaAndModel: "Toyota Land Cruiser Prado 2020",
    want: "дом",
  },
  {
    id: 39,
    category: "машина",
    price: "37 300 000 ₸",
    location: "Astana",
    markaAndModel: "Audi A4 2022",
    want: "дом",
  },
  {
    id: 40,
    category: "машина",
    price: "36 030 000 ₸",
    location: "Astana",
    markaAndModel: "Hyundai Palisade 2022",
    want: "дом",
  },
  {
    id: 41,
    category: "дом",


    price: "30 800 000 ₸",
    location: "Уркер 391",
    square: "88",
    want: "квартира",
  },
  {
    id: 42,
    category: "дом",
    price: "16 990 000 ₸",
    location: "Торткул 7/2",
    square: "62",
    want: "квартира",
  },
  {
    id: 43,
    category: "дом",
    price: "40 000 000 ₸",
    location: "Медеу",
    square: "90",
    want: "квартира",
  },
  {
    id: 44,
    category: "дом",
    price: "28 500 000 ₸",
    location: "Уркер 400",
    square: "88",
    want: "квартира",
  },
  {
    id: 45,
    category: "дом",
    price: "37 800 000 ₸",
    location: "Джалиля 300",
    square: "120",
    want: "квартира",
  },
  {
    id: 46,
    category: "дом",
    price: "25 500 000 ₸",
    location: "Белякова 5",
    square: "56",
    want: "квартира",
  },
  {
    id: 47,
    category: "дом",
    price: "37 800 000 ₸",
    location: "Муса Джалиля 64",
    square: "210",
    want: "квартира",
  },
  {
    id: 48,
    category: "дом",
    price: "37 800 000 ₸",
    location: "Тамшалы 66 — Жарокова",
    square: "94",
    want: "квартира",
  },
  {
    id: 49,
    category: "дом",
    price: "42 000 000 ₸",
    location: "валиханова 31 — Ахмет Байтурсынова",
    square: "100",
    want: "квартира",
  },
  {
    id: 50,
    category: "дом",
    price: "38 500 000 ₸",
    location: " Коксу 5/1",
    square: "135",
    want: "квартира",
  },
  {
    id: 51,
    category: "дом",
    price: "16 900 000 ₸",
    location: "Абыралы 7 — Толстого",
    square: "59",
  },
  {
    id: 52,
    category: "дом",
    price: "32 000 000 〒",
    location: "Казыбек би 92/1",
    square: "93",
  },
  {
    id: 53,
    category: "дом",
    price: "45 000 000 ₸",
    location: " М.Дулатова 31 — К.Байсеитова",
    square: "98",
  },
  {
    id: 54,
    category: "дом",
    price: "21 000 000 ₸",
    location: "Малахова 42 — Жетісай",
    square: "125",
  },
  {
    id: 55,
    category: "дом",
    price: "35 000 000 ₸",
    location: "Алимжанова 64а",
    square: "106",
  },
  {
    id: 56,
    category: "дом",
    price: "15 000 000 ₸",
    location: "Переулок куляш байсеитова 6 — Карбышева",
    square: "56",
  },
  {
    id: 57,
    category: "дом",
    price: "37 000 000 ₸",
    location: "Ильинка — Мусрепова",
    square: "160",
  },
  {
    id: 58,
    category: "дом",
    price: "42 000 000 ₸",
    location: "Алимжанова 64а",
    square: "100",
  },
  {
    id: 59,
    category: "дом",
    price: "40 800 000 ₸",
    location: "КГ Уркер 8",
    square: "102",
  },
  {
    id: 60,
    category: "дом",
    price: "42 000 000 ₸",
    location: "Атбасарская 39",
    square: "80",
  },
];